package org.jetbrains.fortran.lang.types.ty

class FortranArrayType(val base: FortranType, val size: Int) : FortranType() {
    override fun toString(): String {
        return base.toString() + " array of size " + size.toString()
    }

    override fun equals(other: Any?): Boolean {
        if (other !is FortranArrayType) {
            return false
        }

        return base == other.base && size == other.size
    }

    // generated by ide
    override fun hashCode(): Int {
        var result = base.hashCode()
        result = 31 * result + size
        return result
    }
}